### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by schmunk42** [tmrts/boilr#20]
Hi @tmrts,

I just noticed you starred https://github.com/schmunk42/docker-boilr 
Let me know if you'd like to integrate Docker support for boilr.

The above repo is a bit experimental at the moment, especially regarding host-volumes. But any feedback is very welcome!

**Comment by tmrts** [comment]
Hey Tobias,

Thanks for your work. I'd be interested/happy to help you with integrating your work to boilr.
I'm not sure about the aliasing, but other than that it's very cool!

Let me know if you want to integrate it or I can try doing it

**Comment by tmrts** [comment]
@schmunk42 any updates on this? let me know if you need help or if you don't have time to work on this. In the meanwhile feel free to edit the wiki to point to docker-boilr

**Comment by schmunk42** [comment]
Sorry for my late reply.

The first thing I noticed when building the image was, that I need to mount two volumes from my host, since I think it makes no sense to create files with boilr just in the container.

How would you call boilr running with Docker?

An alternative could also be to use `docker-compose` for that, a `yml` file could look like:

```
version: '2'
services:
  boilr:
    image: schmunk42/boilr
    volumes:
      - ~/.config/boilr:/root/.config/boilr
      - ./:/project
```
